services:
  adminfrontend:
    build: ./ims-admin
    container_name: ims-admin_c
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:5079/api
      - PORT=3000
      - HOSTNAME=0.0.0.0
    # Access application at http://localhost:3000/IMS-Admin/auth/login
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/IMS-Admin/auth/login"]
      interval: 30s
      timeout: 10s
      retries: 3
    stdin_open: true
    tty: true