version: '3.8'

services:
  adminfrontend:
    build: ./ims-admin
    container_name: ims-admin_c
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Use local API with dev database for development
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:5079/api
    stdin_open: true
    tty: true