version: '3.8'

services:
  frontend:
    build:
      context: ./ims-admin
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:5079