name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker images
      run: docker compose -f ./docker-compose.yml build
      env:
        NODE_ENV: production
        NEXT_PUBLIC_API_URL: http://localhost:8080/api

  test:
    needs: build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v3
    - name: Start containers
      run: docker compose -f ./docker-compose.yml up -d
      env:
        NODE_ENV: development
        NEXT_PUBLIC_API_URL: http://localhost:5079/api
    - name: Run Cypress tests in container
      run: docker compose -f ./docker-compose.yml exec -T frontend npm run cypress:run
      env:
        NODE_ENV: development
        NEXT_PUBLIC_API_URL: http://localhost:5079/api

  artifacts:
    needs: test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: |
          ims-admin/cypress/videos
          ims-admin/cypress/screenshots