name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './ims-admin/package-lock.json'
          
      - name: Configure npm
        run: |
          npm config set cache .npm --location=project
          npm config set prefer-offline true
          
      - name: Install dependencies
        working-directory: ./ims-admin
        run: npm ci --prefer-offline --no-audit
        
      - name: Build Next.js app
        working-directory: ./ims-admin
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8080/api

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ims-admin/out
          branch: gh-pages