name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker images
      run: docker compose build

  test:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start containers
      run: docker compose up -d
    - name: Run Cypress tests in container
      run: docker compose exec -T frontend npm run cypress:run

  artifacts:
    needs: test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: |
          ims-admin/cypress/videos
          ims-admin/cypress/screenshots