name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Desktop
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker compose build
        docker compose push

    - name: Start containers
      run: docker compose up -d

    - name: Run Cypress tests in container
      run: docker compose exec -T frontend npm run cypress:run

    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: |
          ims-admin/cypress/videos
          ims-admin/cypress/screenshots