name: Deploy, Test, and Dockerize

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./ims-admin
        run: npm ci

      - name: Build Next.js
        working-directory: ./ims-admin
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: "http://localhost:5079/api"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ims-admin/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  cypress-run:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies for Cypress
        working-directory: ./ims-admin
        run: npm ci

      - name: Cypress run (GitHub Pages)
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./ims-admin
          config: |
            {
              "baseUrl": "https://sultan-303.github.io/IMS-Admin",
              "chromeWebSecurity": false
            }
          browser: chrome
        env:
          NEXT_PUBLIC_API_URL: "http://localhost:5079/api"
          CYPRESS_BASE_URL: "https://sultan-303.github.io/IMS-Admin"

  docker:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ims-admin
          push: true
          tags: |
            ghcr.io/sultan-303/ims-admin:latest
            ghcr.io/sultan-303/ims-admin:${{ github.sha }}
        env:
          NEXT_PUBLIC_API_URL: "http://localhost:5079/api"