name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: './ims-admin/package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Install dependencies
        working-directory: ./ims-admin
        run: npm ci

      - name: Build with Next.js
        working-directory: ./ims-admin
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:5079/api

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ims-admin/out

  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: './ims-admin/package-lock.json'
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./ims-admin
          build: npm run build
          start: npx serve@latest out -l 3001 --public /IMS-Admin
          wait-on: 'http://localhost:3001/IMS-Admin'
          config: baseUrl=http://localhost:3001/IMS-Admin
          browser: chrome
        env:
          NEXT_PUBLIC_API_URL: http://localhost:5079/api
          CYPRESS_BASE_URL: http://localhost:3001/IMS-Admin

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ims-admin
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ims-admin:latest
            ghcr.io/${{ github.repository_owner }}/ims-admin:${{ github.sha }}
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8080/api