name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: './ims-admin/package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Install dependencies
        working-directory: ./ims-admin
        run: npm ci

      - name: Build with Next.js
        working-directory: ./ims-admin
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8080/api

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ims-admin/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4