name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build Next.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./ims-admin
        run: npm ci

      - name: Build Next.js
        working-directory: ./ims-admin
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: "http://localhost:5079/api"

  test:
    name: Run Cypress Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./ims-admin
        run: npm ci

      - name: Start Next.js
        working-directory: ./ims-admin
        run: npm run start &
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./ims-admin
          browser: chrome
        env:
          CYPRESS_BASE_URL: http://localhost:3000
          NEXT_PUBLIC_API_URL: http://localhost:5079/api

  docker:
    name: Build & Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ims-admin
          push: true
          tags: |
            ghcr.io/sultan-303/ims-admin:latest
            ghcr.io/sultan-303/ims-admin:${{ github.sha }}
        env:
          NEXT_PUBLIC_API_URL: "http://localhost:5079/api"